oc_token: "sha256~a2es53E6WkVowQL5TwJcbEjpToWYA1rR3Zj1-EHdy3I"
oc_server: "https://c104-e.us-east.containers.cloud.ibm.com:31911"

docker_username: "sunilmanika"
docker_password: "Sunil@karthi24"

namespace: test-ansible2
postgres_label: "app=retail-postgres"

backend_image: "docker.io/{{ docker_username }}/retail-backend:1.0.0"
frontend_image: "docker.io/{{ docker_username }}/retail-frontend:1.0.0"
postgresql_image: "docker.io/{{ docker_username }}/retail-postgresql:1.0.0"

openshift_version: "4.18.28"
jmeter_version: "5.6.3"

github_zip_url: "https://github.com/SunilManika/retailapp/archive/refs/heads/main.zip"
workspace: "/root/retailapp"
