- command: podman build --build-arg VITE_API_BASE_URL= -t docker.io/{{ docker_username }}/retail-frontend:1.0.0 .
  args:
    chdir: "{{ app_dir }}/frontend"
- command: podman push docker.io/{{ docker_username }}/retail-frontend:1.0.0
