- command: terraform init
  args:
    chdir: terraform/load_database

- command: >
    terraform apply -auto-approve
    -var namespace={{ namespace }}
    -var ocp_server={{ ocp_server }}
    -var ocp_token={{ ocp_token }}
  args:
    chdir: terraform/load_database
  no_log: false
